### ISSUE TITLE
Review Risks

### ISSUE THREAD

**Issue by moving-northwards** [pan-training/Documents_and_Figures#2]
- [x] @teodorivanoaica Schedule meeting to review risks from the risk analysis workshop 

Risks can be found [here](https://docs.google.com/spreadsheets/d/1uiPD45n7QO1c1AtH6jfPY_oGyPchwx3JPpVinNlyUQs/edit#gid=502565120) on the last tab.

- [x] @moving-northwards Update document with top 5 risks using PaNOSC matrix.

**Comment by teodorivanoaica** [comment]
I think this has been completed, the meeting today organised by @moving-northwards (Stella) was efficient. We can close the issue after we have the risks updated in the PaNOSC risk analysis document. (the top 5 risks were selected during the discussion) 
If needed a new meeting can be scheduled.
