### ISSUE TITLE
D8.1 Best practises for data stewardship

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/Documents_and_Figures#6]
Report on lessons learned and future prospects for adopting best practises on data stewardship at the PaNOSC facilities

**Comment by thomasholmrod** [comment]
@teodorivanoaica what is status on this one?

**Comment by teodorivanoaica** [comment]
Work in progress, a draft document will be circulated next week.
Based on that, we can also prepare basic data stewardship training.

**Comment by moving-northwards** [comment]
I believe this is now complete. 
@teodorivanoaica Can this issue now be closed?

**Comment by eli-it-serv-git** [comment]
the issue can be closed, it looks like I do not have the necessary permissions to do that.
Thank you

**Comment by moving-northwards** [comment]
Thank you - I will close it then.
